### ISSUE TITLE
can't find multiverse_table

### ISSUE THREAD

**Issue by ntaback** [mverseanalysis/mverse#1]
@mjmoon , @lihd1003  any thoughts 

``` r
library(mverse)
#> Loading required package: magrittr
#> 
#> Attaching package: 'mverse'
#> The following object is masked from 'package:magrittr':
#> 
#>     extract
#> The following object is masked from 'package:base':
#> 
#>     summary
mv <- create_multiverse(soccer)
#> Warning: changing locked binding for 'block_exec' in 'knitr' whilst loading
#> 'multiverse'

skin_tone <- mutate_branch(
  (rater1 + rater2)/2,
  ifelse(rater1 > rater2, rater1, rater2)
)

mv <- mv %>%
  add_mutate_branch(skin_tone) %>%
  execute_multiverse()

summary(mv)
#> Error: 'multiverse_table' is not an exported object from 'namespace:multiverse'
```

<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mjmoon** [comment]
I updated the package with method names from the latest `multiverse_3.*` [here](https://github.com/mverseanalysis/mverse/commit/b7bffaa65e5f4371e0573f0bc9111bbe17f6c586).  I haven't merged it to the master branch yet. I would like to add appropriate tests before merging it to the master branch.
