### ISSUE TITLE
DESCRIPTION file

### ISSUE THREAD

**Issue by abhsarma** [mverseanalysis/mverse#30]
There are a couple of small things that you'd need to perform. I am just listing them down here as a reminder:
- [x] change `multiverse` to a depends / imports. You (probably) cannot use remotes to import packages when submitting to CRAN. Also multiverse is now on CRAN so don't need to either :)
- [x] Put quotes around words such as 'mverse' and 'multiverse' so that spell check does not complain
- [x] Package description might needs more details --- you could discuss more about what these abstractions are and how they benefit the user

**Comment by mjmoon** [comment]
DESCRIPTION file has been updated in #43 and CRAN submission has been accepted.
